apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: webapp-qa

replicas:
  - name: webapp
    count: 2

labels:
  - pairs:
      app.kubernetes.io/environment: qa
    includeSelectors: false
    includeTemplates: true

configMapGenerator:
  - name: web-content
    behavior: replace
    files:
      - index.html

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: webapp
    path: patch-annotation.yaml
