apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: webapp-dev

replicas:
  - name: webapp
    count: 1

images:
  - name: nginx
    newTag: 1.27-alpine

labels:
  - pairs:
      app.kubernetes.io/environment: dev
      debug: "true"
    includeSelectors: false
    includeTemplates: true

configMapGenerator:
  - name: web-content
    behavior: replace
    files:
      - index.html
